<<<<<<< HEAD
# Generated by Django 4.0.6 on 2023-03-17 15:42
=======
# Generated by Django 2.2.28 on 2023-03-18 22:42
>>>>>>> 3ab0401310794d9734b75fa7facd1cafe05b632d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 3ab0401310794d9734b75fa7facd1cafe05b632d
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
