# Generated by Django 2.2.28 on 2023-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_phonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='releaseYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='storage',
            field=models.IntegerField(),
        ),
    ]
