# Generated by Django 2.2.28 on 2023-03-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230321_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
